# -*- coding: utf-8 -*-
"""tda_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fONycdwgIvDZbk0U-JvAnMEGmGLX4u2d
"""

"""
TDA Pipeline for DCC State Variables

Computes topological features from multivariate return embeddings.
Output: DataFrame aligned by date with topological state features.

Features:
- Betti numbers (H0, H1)
- Max persistence, total persistence
- Persistence entropy
- Landscape integrals (L1, L2)
- Wasserstein distance (consecutive diagrams)
"""

import numpy as np
import pandas as pd
from ripser import ripser
from persim import wasserstein
from sklearn.decomposition import PCA
from joblib import Parallel, delayed
import warnings
warnings.filterwarnings('ignore')

# CONFIGURATION

WINDOW = 252          # 1 year rolling window (trading days)
STEP = 1              # daily rolling
EMBED_DIM = 80        # embedding dimension for point cloud
PCA_DIM = 5           # reduce to 5D for Rips (multivariate: 5 assets baseline)
MIN_PERSIST = 1e-6    # minimum persistence to count as a bar

# HELPER FUNCTIONS

def embed_multivariate(returns_window, embed_dim):
    """
    Create sliding window embedding from multivariate returns.

    Args:
        returns_window: array of shape (W, n_assets)
        embed_dim: embedding dimension

    Returns:
        X: point cloud of shape (n_points, n_assets * embed_dim)
    """
    W, n_assets = returns_window.shape

    if W < embed_dim:
        return np.empty((0, n_assets * embed_dim))

    # Create delay embedding: [r_t, r_{t-1}, ..., r_{t-embed_dim+1}]
    n_points = W - embed_dim + 1
    X = np.zeros((n_points, n_assets * embed_dim))

    for i in range(n_points):
        for j in range(embed_dim):
            X[i, j*n_assets:(j+1)*n_assets] = returns_window[i + embed_dim - 1 - j, :]

    return X


def normalize_pointcloud(X):
    """Center and standardize point cloud."""
    X = X - X.mean(axis=0)
    X = X / (X.std(axis=0) + 1e-10)
    return X

def reduce_to_pca(X, n_components):
    """PCA reduction for Rips computation."""
    k = min(n_components, X.shape[0], X.shape[1])
    if k < 2:
        return X
    pca = PCA(n_components=k, svd_solver='randomized', random_state=42)
    return pca.fit_transform(X)

def compute_betti(dgm_h0, dgm_h1):
    """Extract Betti numbers from persistence diagrams."""
    # β₀ = number of connected components (H0 finite bars)
    finite_h0 = np.isfinite(dgm_h0[:, 1])
    betti_0 = len(dgm_h0[finite_h0])

    # β₁ = number of loops (H1 finite bars)
    finite_h1 = np.isfinite(dgm_h1[:, 1])
    betti_1 = len(dgm_h1[finite_h1])

    return betti_0, betti_1

def compute_persistence_stats(dgm):
    """
    Compute persistence statistics from a diagram.

    Returns:
        max_pers, total_pers, entropy, n_significant
    """
    finite = np.isfinite(dgm[:, 1])
    bars = dgm[finite]

    if len(bars) == 0:
        return 0.0, 0.0, 0.0, 0

    lengths = bars[:, 1] - bars[:, 0]
    lengths = lengths[lengths > MIN_PERSIST]

    if len(lengths) == 0:
        return 0.0, 0.0, 0.0, 0

    max_pers = float(np.max(lengths))
    total_pers = float(np.sum(lengths))

    # Entropy
    total = lengths.sum()
    if total > 0:
        p = lengths / total
        entropy = float(-(p * np.log(p + 1e-10)).sum())
    else:
        entropy = 0.0

    # Count bars above 75th percentile
    threshold = np.percentile(lengths, 75) if len(lengths) > 1 else 0
    n_sig = int(np.sum(lengths > threshold))

    return max_pers, total_pers, entropy, n_sig

def compute_landscape_integrals(dgm, scales=[1, 2]):
    """
    Compute landscape integrals at different persistence scales.

    Returns dict with 'landscape_l1', 'landscape_l2', etc.
    """
    finite = np.isfinite(dgm[:, 1])
    bars = dgm[finite]

    if len(bars) == 0:
        return {f'landscape_l{s}': 0.0 for s in scales}

    result = {}
    for s in scales:
        # Simple: integrate persistence values raised to power s
        lengths = bars[:, 1] - bars[:, 0]
        integral = float(np.sum(np.power(lengths, s)))
        result[f'landscape_l{s}'] = integral

    return result

def compute_window(s, e, returns_data, dates, prev_dgm_h1=None):
    """
    Compute all TDA features for a single window [s, e).

    Args:
        s, e: start, end indices
        returns_data: array of shape (n_days, n_assets)
        dates: DatetimeIndex
        prev_dgm_h1: previous H1 diagram for Wasserstein

    Returns:
        features_dict, dgm_h1, end_date
    """
    features = {}

    # Extract window
    ret_win = returns_data[s:e]
    if ret_win.shape[0] < EMBED_DIM or np.isnan(ret_win).any():
        return None, None, dates[e - 1]

    # Embed and normalize
    X = embed_multivariate(ret_win, EMBED_DIM)
    if X.shape[0] < 3:  # Need at least 3 points for topology
        return None, None, dates[e - 1]

    X = normalize_pointcloud(X)

    # PCA reduction
    Y = reduce_to_pca(X, PCA_DIM)
    if np.isnan(Y).any():
        return None, None, dates[e - 1]

    # Ripser: compute H0 and H1
    try:
        result = ripser(Y, maxdim=1)
        dgm_h0 = result['dgms'][0]
        dgm_h1 = result['dgms'][1]
    except Exception:
        return None, None, dates[e - 1]

    # Betti numbers
    betti_0, betti_1 = compute_betti(dgm_h0, dgm_h1)
    features['betti_0'] = betti_0
    features['betti_1'] = betti_1

    # H1 persistence stats
    max_pers_h1, total_pers_h1, entropy_h1, n_sig_h1 = compute_persistence_stats(dgm_h1)
    features['max_persistence'] = max_pers_h1
    features['total_persistence'] = total_pers_h1
    features['entropy'] = entropy_h1
    features['n_significant'] = n_sig_h1

    # Landscape integrals
    landscape_dict = compute_landscape_integrals(dgm_h1, scales=[1, 2])
    features.update(landscape_dict)

    # Wasserstein distance to previous diagram
    if prev_dgm_h1 is not None and len(dgm_h1) > 0 and len(prev_dgm_h1) > 0:
        try:
            wass_dist = float(wasserstein(dgm_h1, prev_dgm_h1))
        except Exception:
            wass_dist = 0.0
    else:
        wass_dist = 0.0

    features['wasserstein'] = wass_dist

    return features, dgm_h1, dates[e - 1]

def run_tda_pipeline(log_returns_df, window=WINDOW, step=STEP, n_jobs=-1, verbose=True):
    """
    Main TDA pipeline.

    Args:
        log_returns_df: DataFrame of shape (n_days, n_assets), indexed by date
        window: rolling window size
        step: step size
        n_jobs: parallel jobs ( speeds up the process)
        verbose: print progress

    Returns:
        tda_df: DataFrame with topological features, indexed by date
    """
    # Convert to numpy arrays, preserving dates
    returns_data = log_returns_df.values
    dates = log_returns_df.index
    n_days = len(returns_data)

    if verbose:
        print(f"TDA Pipeline Configuration:")
        print(f"  Window: {window} days")
        print(f"  Step: {step} days")
        print(f"  Embed dim: {EMBED_DIM}")
        print(f"  PCA dim: {PCA_DIM}")
        print(f"  Data shape: {returns_data.shape}")

    # Define windows
    slices = [(s, s + window) for s in range(0, n_days - window + 1, step)]

    if verbose:
        print(f"  Total windows: {len(slices)}")
        print(f"\nComputing TDA features...")

    # Compute in parallel
    results = Parallel(n_jobs=n_jobs, verbose=10)(
        delayed(compute_window)(s, e, returns_data, dates)
        for s, e in slices
    )

    # Extract results and track previous H1 diagram
    feature_list = []
    date_list = []
    prev_dgm = None

    for features, dgm_h1, end_date in results:
        if features is not None:
            # Recompute Wasserstein with actual previous diagram
            if prev_dgm is not None and len(dgm_h1) > 0 and len(prev_dgm) > 0:
                try:
                    features['wasserstein'] = float(wasserstein(dgm_h1, prev_dgm))
                except Exception:
                    features['wasserstein'] = 0.0
            else:
                features['wasserstein'] = 0.0

            feature_list.append(features)
            date_list.append(end_date)
            prev_dgm = dgm_h1
    # Create DataFrame
    tda_df = pd.DataFrame(feature_list, index=pd.DatetimeIndex(date_list))

    if verbose:
        print(f"\n✅ TDA pipeline complete")
        print(f"Features computed: {tda_df.shape}")
        print(f"Date range: {tda_df.index[0].date()} → {tda_df.index[-1].date()}")
        print(f"\nFeature columns: {list(tda_df.columns)}")
        print(f"\nStatistics:")
        print(tda_df.describe())

    return tda_df

# STANDALONE EXECUTION

if __name__ == "__main__":
    # For testing: load data from parquet
    import sys
    sys.path.insert(0, '/content/MSCTHESIS')

    log_returns = pd.read_parquet('/content/MSCTHESIS/data/processed/log_returns.parquet')

    print("=" * 70)
    print("TDA PIPELINE — STANDALONE TEST")
    print("=" * 70 + "\n")

    tda_features = run_tda_pipeline(log_returns, n_jobs=-1, verbose=True)

    # Save to parquet
    tda_features.to_parquet('/content/MSCTHESIS/data/processed/tda_features.parquet')
    print(f"\n✅ Saved to data/processed/tda_features.parquet")